spring:
  application:
    name: API_Gateway
  cloud:
    gateway:
      routes:
        - id: api-1
          uri: lb://welcome-service
          predicates:
            - Path=/users/**,/auth/**,/api/v4/**
          filters:
            - AddRequestHeader=Authorization, Bearer ${jwt.token} # Dynamically injected or set at runtime

        - id: api-2
          uri: lb://audio-transcrib
          predicates:
            - Path=/api/v2/**,/api/**

        - id: api-3
          uri: lb://Service
          predicates:
            - Path=/api/v3/**

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
